spring.application.name=session11

spring.datasource.url=jdbc:postgresql://localhost:5432/session11
spring.datasource.username=postgres
spring.datasource.password=S1mpL0rd

spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.ra.session11.service=TRACE